### ISSUE TITLE
Cannot run without Xserver.

### ISSUE THREAD

**Issue by unixunite** [ppalucha/ksar2#4]
Great project however cannot run if the Linux does not have X server running which is simply limit you run in Linuxes without X Servers or GUI interface.

root@hanode01 ~]# java -jar /root/ksar2-master/kSar2-0.0.4.jar --input /root/sa10 --pdf sa100.pdf
connect /tmp/.X11-unix/X0: Connection refused
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
......

Running normally if X server is configured.
If you can add this enhancement to be running without any GUI or X servers Thank you.

**Comment by Decstasy** [comment]
I had the same Problem as I need it for automatic report generation. I took the original source and patched the regex for modern sysstat layout to be detected. If I have time theese days I can fork it and upload it for you.

**Comment by unixunite** [comment]
Great and thank you very much indeed for this project, appreciate it.

**Comment by ppalucha** [comment]
Hi, ksar is a GUI application. Currently all the structures for holding parsed data are based around tree widget. So there's no easy way to make it run without GUI - it would require redesigning the whole application. I will close it as it's not really a bug.
